# Generated by Django 3.0.2 on 2020-03-23 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200323_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='date_changed',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 3, 54, 2, 285999)),
        ),
    ]
