# Generated by Django 3.0.2 on 2020-03-23 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200323_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('position', models.IntegerField(blank=True, default=0, help_text='Book Position')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='date_changed',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 23, 1, 9, 671617)),
        ),
    ]
