# Generated by Django 3.0.2 on 2020-04-16 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200323_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='date_changed',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 16, 12, 20, 208588, tzinfo=utc)),
        ),
    ]
