# Generated by Django 3.0.2 on 2020-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20200416_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='date_changed',
            field=models.DateField(),
        ),
    ]
